
version: '3'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    container_name: angular-dev
    volumes:
       - ./garage/:/usr/src/app/garage
       