
version: '3'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "4200:80"
    container_name: angular-prod
    #volumes:
    #   - ./garage/:/usr/src/app
       