/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.crew.generator;

import org.gradle.api.Project;
import org.gradle.api.Plugin;


public class GeneratorPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("generator", GeneratorTask.class);
    }
}
